### ISSUE TITLE
请教一个问题，书中第10章 linkImport，是否支持其他module的wasm函数？

### ISSUE THREAD

**Issue by tjchern** [zxh0/wasmgo-book#3]
我看代码，linkImport的时候，好像不支持import其他module中的wasm函数？
那应该怎么实现呢？
能否拉我进读者群，谢啦

**Comment by zxh0** [comment]
https://github.com/zxh0/wasmgo-book/wiki
请点开链接，扫码进群

**Comment by tjchern** [comment]
好的，谢谢
